/* =============================================================
   PELLIKAL — consent.js  (v2: granular categories)
   The visitor-facing half of Google Consent Mode v2.

   WHERE THE OTHER HALF IS
   The DEFAULTS (everything optional denied) are set by an inline block
   at the very top of every page's <head>, above the Google Tag Manager
   snippet, generated by tools/build.py. That block also re-applies a
   previously stored choice BEFORE gtm.js loads. This file never sets
   the defaults itself unless that block is missing.

   WHAT THIS FILE DOES
   - First visit: a banner with three equal choices —
       Accept All · Reject Non-Essential · Manage Preferences
   - Manage Preferences: a modal dialog with two independent switches,
       Analytics    -> analytics_storage
       Advertising  -> ad_storage + ad_user_data + ad_personalization
     Necessary is shown, always on, and cannot be switched off.
   - Sends the consent UPDATE to Google when a choice is saved.
   - Remembers the choice in a first-party cookie (mirrored to
     localStorage) so the banner does not return on every page.
   - Reopens from the footer, the privacy policy, or ?consent=reset.

   STORED VALUE — and nothing else
       pellikal_consent = v2:a1:d0:2026-09-14
       version : analytics flag : advertising flag : date
   No personal data is ever read from the page or written anywhere.

   NO DARK PATTERNS
   Reject is the same size, weight and hit area as Accept. Nothing is
   pre-ticked. There is no close X on the first-run banner, because a
   dismissal that silently means "accept" is the thing to avoid. In the
   dialog, Escape/Close changes nothing.

   FAIL-SAFE DIRECTION
   If this file is blocked, the head defaults still stand and everything
   optional stays denied. Failure is always "less tracking".
   Full documentation: docs/CONSENT-MODE.md
   ============================================================= */
(function () {
  "use strict";

  /* ---------------------------------------------------------
     SETTINGS — published by the <head> block from site.config.json
  --------------------------------------------------------- */
  var FALLBACK = { name: "pellikal_consent", version: "v2", days: 180, redact: true };
  var headRan = !!window.PELLIKAL_CONSENT_SETTINGS;
  var S = window.PELLIKAL_CONSENT_SETTINGS || FALLBACK;

  window.dataLayer = window.dataLayer || [];
  function gtag() { window.dataLayer.push(arguments); }

  function consentState(analytics, advertising) {
    var ad = advertising ? "granted" : "denied";
    return {
      analytics_storage: analytics ? "granted" : "denied",
      ad_storage: ad,
      ad_user_data: ad,
      ad_personalization: ad
    };
  }

  if (!headRan) {
    if (window.console && console.warn) {
      console.warn("[Pellikal] Consent Mode defaults are missing from <head>. Run: python3 tools/build.py");
    }
    gtag("consent", "default", consentState(false, false));
    if (S.redact) gtag("set", "ads_data_redaction", true);
  }

  /* ---------------------------------------------------------
     STORAGE — first-party cookie, localStorage as a mirror
  --------------------------------------------------------- */
  function readRaw() {
    try {
      var parts = ("; " + document.cookie).split("; " + S.name + "=");
      if (parts.length > 1) return decodeURIComponent(parts.pop().split(";").shift());
    } catch (e) {}
    try { if (window.localStorage) return window.localStorage.getItem(S.name) || ""; } catch (e) {}
    return "";
  }

  function writeRaw(value) {
    try {
      var expires = new Date(Date.now() + S.days * 86400000).toUTCString();
      document.cookie = S.name + "=" + encodeURIComponent(value) +
        ";Path=/;Expires=" + expires + ";SameSite=Lax" +
        (location.protocol === "https:" ? ";Secure" : "");
    } catch (e) {}
    try { if (window.localStorage) window.localStorage.setItem(S.name, value); } catch (e) {}
  }

  function clearRaw() {
    try {
      document.cookie = S.name + "=;Path=/;Expires=Thu, 01 Jan 1970 00:00:00 GMT;SameSite=Lax" +
        (location.protocol === "https:" ? ";Secure" : "");
    } catch (e) {}
    try { if (window.localStorage) window.localStorage.removeItem(S.name); } catch (e) {}
  }

  /* {analytics:bool, advertising:bool} or null when nothing valid is stored.
     A value from an older version prefix does not match and is treated as
     "not chosen" — that is how bumping the version re-asks everyone. */
  function choice() {
    var raw = readRaw();
    if (raw.indexOf(S.version + ":") !== 0) return null;
    return { analytics: raw.indexOf(":a1") > -1, advertising: raw.indexOf(":d1") > -1 };
  }

  function today() {
    var d = new Date();
    function pad(n) { return (n < 10 ? "0" : "") + n; }
    return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate());
  }

  /* ---------------------------------------------------------
     THE UPDATE
     Always an explicit update, even when everything stays denied, so
     the visitor's actual decision is visible in Tag Assistant.
  --------------------------------------------------------- */
  function apply(prefs, how) {
    gtag("consent", "update", consentState(prefs.analytics, prefs.advertising));
    if (S.redact) gtag("set", "ads_data_redaction", !prefs.advertising);
    window.dataLayer.push({
      event: "consent_update",
      consent_choice: how,
      consent_analytics: prefs.analytics ? "granted" : "denied",
      consent_advertising: prefs.advertising ? "granted" : "denied"
    });
  }

  function save(prefs, how) {
    writeRaw(S.version + ":a" + (prefs.analytics ? 1 : 0) + ":d" + (prefs.advertising ? 1 : 0) + ":" + today());
    apply(prefs, how);
    closeDialog();
    removeBanner();
  }

  /* ---------------------------------------------------------
     DOM HELPERS — DOM methods and textContent only, never innerHTML
  --------------------------------------------------------- */
  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function button(cls, label, action) {
    var b = el("button", cls, label);
    b.type = "button";
    b.setAttribute("data-consent-choice", action);
    return b;
  }

  function privacyHref() {
    var a = document.querySelector('.footer a[href$="privacy/"]');
    return a ? a.getAttribute("href") : "/privacy/";
  }

  var COPY = "We use optional analytics and advertising technologies to understand site usage " +
             "and measure our advertising. You can accept optional tracking, reject it, or " +
             "choose by category.";

  /* ---------------------------------------------------------
     BANNER (first run only; non-modal — the page stays usable)
  --------------------------------------------------------- */
  var banner = null;

  function measure() {
    var h = banner ? banner.offsetHeight : 0;
    document.documentElement.style.setProperty("--consent-h", h + "px");
  }
  window.addEventListener("resize", function () { if (banner) measure(); });

  function removeBanner() {
    if (banner && banner.parentNode) banner.parentNode.removeChild(banner);
    banner = null;
    document.documentElement.classList.remove("consent-open");
    document.documentElement.style.setProperty("--consent-h", "0px");
  }

  function showBanner() {
    removeBanner();
    banner = el("div", "consent");
    banner.setAttribute("role", "region");
    banner.setAttribute("aria-label", "Tracking preferences");

    var inner = el("div", "container consent__inner");
    var copy = el("div", "consent__copy");
    copy.appendChild(el("p", "consent__text", COPY));
    var link = el("a", "consent__link", "Privacy Policy");
    link.href = privacyHref();
    copy.appendChild(link);
    inner.appendChild(copy);

    var actions = el("div", "consent__actions");
    actions.appendChild(button("btn btn--cyan consent__btn", "Accept All", "all"));
    actions.appendChild(button("btn consent__btn consent__btn--alt", "Reject Non-Essential", "reject"));
    actions.appendChild(button("btn consent__btn consent__btn--manage", "Manage Preferences", "manage"));
    inner.appendChild(actions);

    banner.appendChild(inner);
    document.body.appendChild(banner);
    document.documentElement.classList.add("consent-open");
    measure();
  }

  /* ---------------------------------------------------------
     PREFERENCES DIALOG (modal)
     role=dialog + aria-modal, labelled by its heading, focus moved in
     on open, contained while open, Escape closes, focus returned to
     whatever opened it. Switches are native checkboxes — free keyboard
     and screen-reader behaviour — dressed up in CSS.
  --------------------------------------------------------- */
  var overlay = null, opener = null;

  function focusables() {
    return overlay ? Array.prototype.slice.call(overlay.querySelectorAll(
      'button:not([disabled]), input:not([disabled]), a[href]')) : [];
  }

  function onKey(e) {
    if (!overlay) return;
    if (e.key === "Escape") { e.preventDefault(); closeDialog(); return; }
    if (e.key !== "Tab") return;
    var f = focusables(); if (!f.length) return;
    var first = f[0], last = f[f.length - 1];
    var idx = f.indexOf(document.activeElement);
    /* Initial focus is on the heading (tabindex=-1), which is not in the
       tab sequence — from there, Tab goes to the first control and
       Shift+Tab to the last, never out to the page underneath. */
    if (idx === -1) { e.preventDefault(); (e.shiftKey ? last : first).focus(); return; }
    if (e.shiftKey && idx === 0) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && idx === f.length - 1) { e.preventDefault(); first.focus(); }
  }

  function category(id, title, desc, on, locked) {
    var row = el("div", "consent__cat" + (locked ? " consent__cat--locked" : ""));
    var head = el("div", "consent__cat-head");
    var lab = el("label", "consent__switch");
    var input = document.createElement("input");
    input.type = "checkbox";
    input.id = "consent-" + id;
    input.checked = !!on;
    if (locked) { input.disabled = true; }
    else { input.setAttribute("data-consent-cat", id); }
    lab.setAttribute("for", input.id);
    lab.appendChild(input);
    lab.appendChild(el("span", "consent__track"));
    lab.appendChild(el("span", "consent__switch-label", title));
    head.appendChild(lab);
    if (locked) head.appendChild(el("span", "consent__always", "Always on"));
    row.appendChild(head);
    var p = el("p", "consent__cat-desc", desc);
    p.id = input.id + "-desc";
    input.setAttribute("aria-describedby", p.id);
    row.appendChild(p);
    return row;
  }

  function openDialog(fromEl) {
    if (overlay) return;
    opener = fromEl || document.activeElement;
    var current = choice() || { analytics: false, advertising: false };

    overlay = el("div", "consent-overlay");
    var dlg = el("div", "consent-dialog");
    dlg.setAttribute("role", "dialog");
    dlg.setAttribute("aria-modal", "true");
    dlg.setAttribute("aria-labelledby", "consent-dialog-title");
    dlg.setAttribute("aria-describedby", "consent-dialog-intro");

    var top = el("div", "consent-dialog__head");
    var h = el("h2", "consent-dialog__title", "Tracking preferences");
    h.id = "consent-dialog-title";
    top.appendChild(h);
    var x = button("consent-dialog__close", "\u00D7", "close");
    x.setAttribute("aria-label", "Close without changing your choice");
    top.appendChild(x);
    dlg.appendChild(top);

    var intro = el("p", "consent-dialog__intro",
      "Choose which optional technologies may run. Necessary functions always run. " +
      "Your current choices are shown below. Changes take effect when you save.");
    intro.id = "consent-dialog-intro";
    dlg.appendChild(intro);

    dlg.appendChild(category("necessary", "Necessary",
      "Keeps the website working and secure, and remembers the choice you make here. " +
      "Sets no analytics or advertising identifiers.", true, true));
    dlg.appendChild(category("analytics", "Analytics",
      "Google Analytics 4: how many people visit, which pages they read and how they " +
      "arrived, reported in aggregate.", current.analytics, false));
    dlg.appendChild(category("advertising", "Advertising",
      "Google Ads: measuring which advertisements lead to enquiries, and remarketing. " +
      "Covers ad storage, ad user data and ad personalisation.", current.advertising, false));

    var link = el("a", "consent__link", "Privacy Policy");
    link.href = privacyHref();
    dlg.appendChild(link);

    var actions = el("div", "consent-dialog__actions");
    actions.appendChild(button("btn btn--navy consent__btn", "Save Preferences", "save"));
    actions.appendChild(button("btn btn--cyan consent__btn", "Accept All", "all"));
    actions.appendChild(button("btn btn--ghost consent__btn", "Reject Non-Essential", "reject"));
    dlg.appendChild(actions);

    overlay.appendChild(dlg);
    document.body.appendChild(overlay);
    document.documentElement.classList.add("consent-dialog-open");
    document.addEventListener("keydown", onKey, true);
    try { h.setAttribute("tabindex", "-1"); h.focus(); } catch (e) {}
  }

  function closeDialog() {
    if (!overlay) return;
    document.removeEventListener("keydown", onKey, true);
    if (overlay.parentNode) overlay.parentNode.removeChild(overlay);
    overlay = null;
    document.documentElement.classList.remove("consent-dialog-open");
    var back = opener; opener = null;
    if (back && back.focus && document.contains(back)) { try { back.focus(); } catch (e) {} }
  }

  function readSwitches() {
    var a = overlay && overlay.querySelector('[data-consent-cat="analytics"]');
    var d = overlay && overlay.querySelector('[data-consent-cat="advertising"]');
    return { analytics: !!(a && a.checked), advertising: !!(d && d.checked) };
  }

  /* ---------------------------------------------------------
     ONE DELEGATED LISTENER — banner buttons, dialog buttons, and any
     [data-consent-open] control anywhere on the page.
  --------------------------------------------------------- */
  document.addEventListener("click", function (e) {
    var t = e.target;
    if (!t || !t.closest) return;

    var hit = t.closest("[data-consent-choice]");
    if (hit) {
      var action = hit.getAttribute("data-consent-choice");
      if (action === "all")    return save({ analytics: true,  advertising: true  }, "accept_all");
      if (action === "reject") return save({ analytics: false, advertising: false }, "reject");
      if (action === "save")   return save(readSwitches(), "custom");
      if (action === "manage") return openDialog(hit);
      if (action === "close")  return closeDialog();
      return;
    }

    var open = t.closest("[data-consent-open]");
    if (open) { e.preventDefault(); openDialog(open); }
  });

  /* ---------------------------------------------------------
     PUBLIC API — footer, privacy page, and the browser console.
     necessaryOnly() is kept as an alias so older notes still work.
  --------------------------------------------------------- */
  window.PELLIKAL_CONSENT = {
    get: choice,
    acceptAll:     function () { save({ analytics: true,  advertising: true  }, "accept_all"); },
    rejectAll:     function () { save({ analytics: false, advertising: false }, "reject"); },
    necessaryOnly: function () { save({ analytics: false, advertising: false }, "reject"); },
    save:          function (p) { save({ analytics: !!(p && p.analytics), advertising: !!(p && p.advertising) }, "custom"); },
    open:          function () { openDialog(null); },
    reset: function () {
      clearRaw();
      apply({ analytics: false, advertising: false }, "reset");
      closeDialog();
      showBanner();
    }
  };

  /* ---------------------------------------------------------
     START
  --------------------------------------------------------- */
  function start() {
    document.documentElement.classList.add("consent-ready");

    if (/[?&]consent=reset(&|$)/.test(location.search)) {
      clearRaw();
      if (window.history && history.replaceState) {
        var clean = location.search.replace(/([?&])consent=reset(&|$)/, "$1").replace(/[?&]$/, "");
        try { history.replaceState(null, "", location.pathname + clean + location.hash); } catch (e) {}
      }
    }

    if (!choice()) showBanner();
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
  else start();
})();
